[tools]
committed = "latest"
dprint = "latest"
elixir = "1.18.4-otp-27"
erlang = "27"
jq = "latest"
lefthook = { version = "latest", postinstall = "lefthook install" }
"pipx:check-jsonschema" = "latest"
task = "latest"

[settings]
experimental = true
disable_backends = ["asdf"]
npm.bun = true
