[tools]
dprint = "latest"
elixir = "1.19.5-otp-28"
erlang = "28"
jq = "latest"
lefthook = { version = "latest" }
"pipx:check-jsonschema" = "latest"
task = "latest"
"ubi:crate-ci/committed" = "latest"

[hooks]
postinstall = "lefthook install"

[settings]
experimental = true
disable_backends = ["asdf"]
npm.bun = true
